# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=250)),
                ('personName', models.CharField(max_length=500)),
                ('data', models.TextField()),
            ],
        ),
    ]
